/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoprogra4;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author USER
 */
public class inicio extends javax.swing.JFrame {

    private ImageIcon imagen;
    private ImageIcon icono;

    /**
     * Creates new form main
     */
    int xmouse;
    int ymouse; 
    public inicio() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.pintarImagen(this.lblfondo, "src/datatec/1.jpg");
        this.pintarImagen(this.lbllogo, "src/datatec/4.jpg");
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lblfondo = new javax.swing.JLabel();
        lbllogo = new javax.swing.JLabel();
        lblloguito = new javax.swing.JLabel();
        lbllogo1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        contra = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        passTxt = new javax.swing.JPasswordField();
        exit = new javax.swing.JPanel();
        equis = new javax.swing.JLabel();
        ingresar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 0, 310, 500));
        jPanel1.add(lbllogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 230, 180));
        jPanel1.add(lblloguito, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 120, 70));
        jPanel1.add(lbllogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 34, 215, 140));

        titulo.setFont(new java.awt.Font("Outfit Black", 3, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("INICIAR SESION");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 240, 40));

        contra.setFont(new java.awt.Font("Outfit Light", 0, 18)); // NOI18N
        contra.setText("Contraseña:");
        jPanel1.add(contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 210, 30));

        usuario.setFont(new java.awt.Font("Outfit Light", 0, 18)); // NOI18N
        usuario.setText("Usuario:");
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 210, 30));

        userTxt.setFont(new java.awt.Font("Outfit ExtraLight", 0, 14)); // NOI18N
        userTxt.setForeground(new java.awt.Color(102, 102, 102));
        userTxt.setText("Ingrese su usuario");
        userTxt.setBorder(null);
        userTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userTxtMousePressed(evt);
            }
        });
        userTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtActionPerformed(evt);
            }
        });
        jPanel1.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 370, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 370, 20));

        jSeparator5.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator5.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 370, 40));

        passTxt.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        passTxt.setForeground(new java.awt.Color(102, 102, 102));
        passTxt.setText("jPasswordField1");
        passTxt.setBorder(null);
        passTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passTxtMousePressed(evt);
            }
        });
        jPanel1.add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 370, 40));

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
        });

        equis.setFont(new java.awt.Font("Outfit Medium", 0, 24)); // NOI18N
        equis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equis.setText("X");
        equis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                equisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                equisMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitLayout = new javax.swing.GroupLayout(exit);
        exit.setLayout(exitLayout);
        exitLayout.setHorizontalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(equis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        exitLayout.setVerticalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(equis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        ingresar1.setBackground(new java.awt.Color(0, 102, 204));
        ingresar1.setFont(new java.awt.Font("Outfit ExtraBold", 0, 14)); // NOI18N
        ingresar1.setText("INGRESAR");
        ingresar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingresar1MouseExited(evt);
            }
        });
        ingresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar1ActionPerformed(evt);
            }
        });
        jPanel1.add(ingresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtActionPerformed

    private void userTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTxtMousePressed
        if (userTxt.getText().equals("Ingrese su nombre de usuario")) {
            userTxt.setText(" ");
         userTxt.setForeground(Color.black);
        }
        if(String.valueOf(passTxt.getPassword()). isEmpty()) {
        passTxt.setText("*********");
        userTxt.setForeground(Color.gray);
    }//GEN-LAST:event_userTxtMousePressed
    }
    private void passTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTxtMousePressed
         if(String.valueOf(passTxt.getPassword()). equals("*********")) { 
         passTxt.setText("");
         userTxt.setForeground(Color.black); 
         }
         if (userTxt.getText().isEmpty()){
        userTxt.setText("Ingrese su nombre de usuario");
          userTxt.setForeground(Color.gray);
    }//GEN-LAST:event_passTxtMousePressed
    }
    private void equisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equisMouseClicked
        System.exit(0);
    }//GEN-LAST:event_equisMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
      exit.setBackground(Color.red);
    }//GEN-LAST:event_exitMouseEntered

    private void equisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equisMouseEntered
        exit.setBackground(new Color (56,182,255));
        exit.setForeground(Color.white);
    }//GEN-LAST:event_equisMouseEntered

    private void equisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equisMouseExited
    exit.setBackground(Color.white);
    exit.setForeground(Color.black);
    }//GEN-LAST:event_equisMouseExited

    private void ingresar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar1MouseEntered
         ingresar1.setBackground(new Color (0,151,178));
        ingresar1.setForeground(Color.white);
    }//GEN-LAST:event_ingresar1MouseEntered

    private void ingresar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar1MouseExited
        ingresar1.setBackground(new Color (82,113,255));
         ingresar1.setForeground(Color.black);
    }//GEN-LAST:event_ingresar1MouseExited

    private void ingresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresar1ActionPerformed
        menu abrirmenu = new menu(); 
        abrirmenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ingresar1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }
  public void pintarImagen(JLabel lbl, String root) {
           this.imagen = new ImageIcon(root);
           this.icono = new ImageIcon(
                   this.imagen.getImage().getScaledInstance(
                           lbl.getWidth(), 
                           lbl.getHeight(),
                           Image.SCALE_DEFAULT
                   )
           ); 
           lbl.setIcon(this.icono);
           this.repaint();
           
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contra;
    private javax.swing.JLabel equis;
    private javax.swing.JPanel exit;
    private javax.swing.JButton ingresar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JLabel lbllogo1;
    private javax.swing.JLabel lblloguito;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField userTxt;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
