/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoprogra4;

import java.awt.Color;
import java.awt.Image;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author USER
 */
public class menu extends javax.swing.JFrame {
  private ImageIcon imagen;
    private ImageIcon icono;
    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
         this.setLocationRelativeTo(this);
        this.pintarImagen(this.lblfondo2, "src/datatec/3.jpg");
        this.pintarImagen(this.lbllogo2, "src/datatec/4.jpg");
        this.pintarImagen(this.lblbuscar, "src/datatec/buscar.png");
        this.pintarImagen(this.lblinsertar, "src/datatec/agregar.png");
        this.pintarImagen(this.lblmodificar, "src/datatec/editar.png");
        this.pintarImagen(this.lblborrar, "src/datatec/borrar.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbllogo2 = new javax.swing.JLabel();
        lblbuscar = new javax.swing.JLabel();
        lblmodificar = new javax.swing.JLabel();
        lblborrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblfondo2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblinsertar = new javax.swing.JLabel();
        botoninsertar = new javax.swing.JToggleButton();
        botoneditar = new javax.swing.JToggleButton();
        botonborrar = new javax.swing.JToggleButton();
        botonbuscar = new javax.swing.JToggleButton();
        exit2 = new javax.swing.JPanel();
        equis2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(lbllogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 150, 140));

        lblbuscar.setText("jLabel1");
        jPanel1.add(lblbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 136, 100, 100));

        lblmodificar.setText("jLabel1");
        jPanel1.add(lblmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 317, 100, 100));

        lblborrar.setText("jLabel1");
        jPanel1.add(lblborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 317, 100, 100));

        jLabel1.setFont(new java.awt.Font("Outfit Black", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 330, 40));
        jPanel1.add(lblfondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 340, 500));

        jLabel3.setFont(new java.awt.Font("Outfit Black", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MENU");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 340, 60));

        lblinsertar.setText("jLabel1");
        jPanel1.add(lblinsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 136, 100, 100));

        botoninsertar.setBackground(new java.awt.Color(153, 153, 255));
        botoninsertar.setFont(new java.awt.Font("Outfit Medium", 0, 14)); // NOI18N
        botoninsertar.setText("Insertar");
        botoninsertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botoninsertarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botoninsertarMouseExited(evt);
            }
        });
        botoninsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoninsertarActionPerformed(evt);
            }
        });
        jPanel1.add(botoninsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 240, 100, 30));

        botoneditar.setBackground(new java.awt.Color(153, 153, 255));
        botoneditar.setFont(new java.awt.Font("Outfit Medium", 0, 14)); // NOI18N
        botoneditar.setText("Modificar");
        botoneditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botoneditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botoneditarMouseExited(evt);
            }
        });
        botoneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneditarActionPerformed(evt);
            }
        });
        jPanel1.add(botoneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 420, 100, 30));

        botonborrar.setBackground(new java.awt.Color(153, 153, 255));
        botonborrar.setFont(new java.awt.Font("Outfit Medium", 0, 14)); // NOI18N
        botonborrar.setText("Eliminar");
        botonborrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonborrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonborrarMouseExited(evt);
            }
        });
        botonborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonborrarActionPerformed(evt);
            }
        });
        jPanel1.add(botonborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 420, 100, 30));

        botonbuscar.setBackground(new java.awt.Color(153, 153, 255));
        botonbuscar.setFont(new java.awt.Font("Outfit Medium", 0, 14)); // NOI18N
        botonbuscar.setText("Buscar");
        botonbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonbuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonbuscarMouseExited(evt);
            }
        });
        botonbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonbuscarActionPerformed(evt);
            }
        });
        jPanel1.add(botonbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 240, 100, 30));

        exit2.setBackground(new java.awt.Color(255, 255, 255));

        equis2.setFont(new java.awt.Font("Outfit Medium", 0, 24)); // NOI18N
        equis2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equis2.setText("X");
        equis2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equis2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                equis2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                equis2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout exit2Layout = new javax.swing.GroupLayout(exit2);
        exit2.setLayout(exit2Layout);
        exit2Layout.setHorizontalGroup(
            exit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exit2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(equis2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        exit2Layout.setVerticalGroup(
            exit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exit2Layout.createSequentialGroup()
                .addComponent(equis2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(exit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneditarActionPerformed
        modificar abrirmodificar=new modificar();
        abrirmodificar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botoneditarActionPerformed

    private void botonbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonbuscarActionPerformed
        Buscar abrirbuscar = null;
      try {
          abrirbuscar = new Buscar();
      } catch (InterruptedException ex) {
          Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
      } catch (ExecutionException ex) {
          Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
      }
        abrirbuscar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonbuscarActionPerformed

    private void botonbuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonbuscarMouseEntered
        botonbuscar.setBackground(new Color (12,193,224));
        botonbuscar.setForeground(Color.white);
    }//GEN-LAST:event_botonbuscarMouseEntered

    private void botonbuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonbuscarMouseExited
        botonbuscar.setBackground(new Color (9,142,116));
        botonbuscar.setForeground(Color.black);
    }//GEN-LAST:event_botonbuscarMouseExited

    private void botoninsertarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoninsertarMouseEntered
        botoninsertar.setBackground(new Color (12,193,224));
        botoninsertar.setForeground(Color.white);
    }//GEN-LAST:event_botoninsertarMouseEntered

    private void botoninsertarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoninsertarMouseExited
        botoninsertar.setBackground(new Color (9,142,116));
        botoninsertar.setForeground(Color.black);
    }//GEN-LAST:event_botoninsertarMouseExited

    private void botoneditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoneditarMouseEntered
        botoneditar.setBackground(new Color (12,193,224));
        botoneditar.setForeground(Color.white);
    }//GEN-LAST:event_botoneditarMouseEntered

    private void botoneditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoneditarMouseExited
       botoneditar.setBackground(new Color (9,142,116));
        botoneditar.setForeground(Color.black);
    }//GEN-LAST:event_botoneditarMouseExited

    private void botonborrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonborrarMouseEntered
        botonborrar.setBackground(new Color (12,193,224));
        botonborrar.setForeground(Color.white);
    }//GEN-LAST:event_botonborrarMouseEntered

    private void botonborrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonborrarMouseExited
       botonborrar.setBackground(new Color (9,142,116));
        botonborrar.setForeground(Color.black); 
    }//GEN-LAST:event_botonborrarMouseExited

    private void equis2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equis2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_equis2MouseClicked

    private void equis2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equis2MouseEntered
        exit2.setBackground(new Color (56,182,255));
        exit2.setForeground(Color.white);
    }//GEN-LAST:event_equis2MouseEntered

    private void equis2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equis2MouseExited
        exit2.setBackground(Color.white);
        exit2.setForeground(Color.black);
    }//GEN-LAST:event_equis2MouseExited

    private void botoninsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoninsertarActionPerformed
        insertar abririnsertar=new insertar();
        abririnsertar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botoninsertarActionPerformed

    private void botonborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonborrarActionPerformed
        Eliminar abrireliminar=new Eliminar();
        abrireliminar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonborrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }
 public void pintarImagen(JLabel lbl, String root) {
           this.imagen = new ImageIcon(root);
           this.icono = new ImageIcon(
                   this.imagen.getImage().getScaledInstance(
                           lbl.getWidth(), 
                           lbl.getHeight(),
                           Image.SCALE_DEFAULT
                   )
           ); 
           lbl.setIcon(this.icono);
           this.repaint();
           
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonborrar;
    private javax.swing.JToggleButton botonbuscar;
    private javax.swing.JToggleButton botoneditar;
    private javax.swing.JToggleButton botoninsertar;
    private javax.swing.JLabel equis2;
    private javax.swing.JPanel exit2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblborrar;
    private javax.swing.JLabel lblbuscar;
    private javax.swing.JLabel lblfondo2;
    private javax.swing.JLabel lblinsertar;
    private javax.swing.JLabel lbllogo2;
    private javax.swing.JLabel lblmodificar;
    // End of variables declaration//GEN-END:variables
}
